# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Species.create([{:name=>"Acara"}, {:name=>"Aisha"}, {:name=>"Blumaroo"}, {:name=>"Bori"}, {:name=>"Bruce"}, {:name=>"Buzz"}, {:name=>"Chia"}, {:name=>"Chomby"}, {:name=>"Cybunny"}, {:name=>"Draik"}, {:name=>"Elephante"}, {:name=>"Eyrie"}, {:name=>"Flotsam"}, {:name=>"Gelert"}, {:name=>"Gnorbu"}, {:name=>"Grarrl"}, {:name=>"Grundo"}, {:name=>"Hissi"}, {:name=>"Ixi"}, {:name=>"Jetsam"}, {:name=>"Jubjub"}, {:name=>"Kacheek"}, {:name=>"Kau"}, {:name=>"Kiko"}, {:name=>"Koi"}, {:name=>"Korbat"}, {:name=>"Kougra"}, {:name=>"Krawk"}, {:name=>"Kyrii"}, {:name=>"Lenny"}, {:name=>"Lupe"}, {:name=>"Lutari"}, {:name=>"Meerca"}, {:name=>"Moehog"}, {:name=>"Mynci"}, {:name=>"Nimmo"}, {:name=>"Ogrin"}, {:name=>"Peophin"}, {:name=>"Poogle"}, {:name=>"Pteri"}, {:name=>"Quiggle"}, {:name=>"Ruki"}, {:name=>"Scorchio"}, {:name=>"Shoyru"}, {:name=>"Skeith"}, {:name=>"Techo"}, {:name=>"Tonu"}, {:name=>"Tuskaninny"}, {:name=>"Uni"}, {:name=>"Usul"}, {:name=>"Wocky"}, {:name=>"Xweetok"}, {:name=>"Yurble"}, {:name=>"Zafara"}, {:name=>"Vandagyre"}])
Color.create([{:name=>"Alien"}, {:name=>"Apple"}, {:name=>"Asparagus"}, {:name=>"Aubergine"}, {:name=>"Avocado"}, {:name=>"Baby"}, {:name=>"Biscuit"}, {:name=>"Blue"}, {:name=>"Blueberry"}, {:name=>"Brown"}, {:name=>"Camouflage"}, {:name=>"Carrot"}, {:name=>"Checkered"}, {:name=>"Chocolate"}, {:name=>"Chokato"}, {:name=>"Christmas"}, {:name=>"Clay"}, {:name=>"Cloud"}, {:name=>"Coconut"}, {:name=>"Custard"}, {:name=>"Darigan"}, {:name=>"Desert"}, {:name=>"Disco"}, {:name=>"Durian"}, {:name=>"Electric"}, {:name=>"Faerie"}, {:name=>"Fire"}, {:name=>"Garlic"}, {:name=>"Ghost"}, {:name=>"Glowing"}, {:name=>"Gold"}, {:name=>"Gooseberry"}, {:name=>"Grape"}, {:name=>"Green"}, {:name=>"Grey"}, {:name=>"Halloween"}, {:name=>"Ice"}, {:name=>"Invisible"}, {:name=>"Island"}, {:name=>"Jelly"}, {:name=>"Lemon"}, {:name=>"Lime"}, {:name=>"Mallow"}, {:name=>"Maraquan"}, {:name=>"Msp"}, {:name=>"Mutant"}, {:name=>"Orange"}, {:name=>"Pea"}, {:name=>"Peach"}, {:name=>"Pear"}, {:name=>"Pepper"}, {:name=>"Pineapple"}, {:name=>"Pink"}, {:name=>"Pirate"}, {:name=>"Plum"}, {:name=>"Plushie"}, {:name=>"Purple"}, {:name=>"Quigukiboy"}, {:name=>"Quigukigirl"}, {:name=>"Rainbow"}, {:name=>"Red"}, {:name=>"Robot"}, {:name=>"Royalboy"}, {:name=>"Royalgirl"}, {:name=>"Shadow"}, {:name=>"Silver"}, {:name=>"Sketch"}, {:name=>"Skunk"}, {:name=>"Snot"}, {:name=>"Snow"}, {:name=>"Speckled"}, {:name=>"Split"}, {:name=>"Sponge"}, {:name=>"Spotted"}, {:name=>"Starry"}, {:name=>"Strawberry"}, {:name=>"Striped"}, {:name=>"Thornberry"}, {:name=>"Tomato"}, {:name=>"Tyrannian"}, {:name=>"Usuki Boy"}, {:name=>"Usuki Girl"}, {:name=>"White"}, {:name=>"Yellow"}, {:name=>"Zombie"}, {:name=>"Onion"}, {:name=>"Magma"}, {:name=>"Relic"}, {:name=>"Woodland"}, {:name=>"Transparent"}, {:name=>"Maractite"}, {:name=>"8-bit"}, {:name=>"Swamp Gas"}, {:name=>"Water"}, {:name=>"Wraith"}, {:name=>"Eventide"}, {:name=>"Elderlyboy"}, {:name=>"Elderlygirl"}, {:name=>"Stealthy"}, {:name=>"Dimensional"}, {:name=>"Agueena"}, {:name=>"Pastel"}, {:name=>"Ummagine"}, {:name=>"Polka Dot"}])
NameQuality.create([
  { abbreviation: 'VWN' },
  { abbreviation: 'WN' },
  { abbreviation: 'WN (uncapped)' },
  { abbreviation: 'DN' },
  { abbreviation: 'AN' }
])
ConversionState.create([ { name: 'Converted' }, { name: 'Unconverted' } ])
